# Group Number: 23

# Group Members:
#     Bratin Mondal 
#     21CS10016

#     Kapil Bhanwariwal
#     23BM6JP20

# ------------------------

# Project Number: 1

# Project Title: Medical Insurance Approval using Decision Tree based Learning Model

model: main.py model.py helper.py
	python3 main.py

test_scikit_learn: scikit_learn_tree.py
	python3 scikit_learn_tree.py

clean:
	rm -fr ./Output ./__pycache__ 
	rm -f *.pdf *.png decision_tree_visualization_gini decision_tree_visualization_entropy