# Group Number: 29
# Student Name: Bratin Mondal
# Roll Number: 21CS10016
# Project Title: Song Popularity using Neural Networks

model: main.py Model.py Preprocess.py
	mkdir -p ../OUTPUT
	python3 main.py

test_scikit_learn: scikit_learn.py
	mkdir -p ../OUTPUT
	python3 scikit_learn.py

clean: 
	rm -rf ./__pycache__ ../OUTPUT
