server:
	gcc -o server.out server.c
	./server.out

client:
	gcc -o client.out client.c
	./client.out

udpserver:
	gcc -o udpserver.out udpserver.c
	./udpserver.out

udpclient:
	gcc -o udpclient.out udpclient.c
	./udpclient.out

tcpserver:
	gcc -o tcpserver.out tcpserver.c
	./tcpserver.out

tcpclient:
	gcc -o tcpclient.out tcpclient.c
	./tcpclient.out

clean:
	rm -f *.out