# Student Name: Bratin Mondal
# Student ID: 21CS10016
# Project Code: CGHC-DC
# Project Title: Country Grouping using Complete Linkage Divisive (Top-Down) Clustering Technique

model: main.py requirements.txt
	@echo "Running the model..."
	@mkdir -p ../OUTPUT
	@mkdir -p ../SUBMISSION
	@python3 main.py


clean:
	rm -rf ../OUTPUT ../__pycache__